config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  root 'projects#index'

  resources :builds do
    member do
      post :rebuild
    end
  end

  resources :projects

  mount Sidekiq::Web => '/sidekiq'

end

app/models/build.rb
class Build < ActiveRecord::Base
  belongs_to :project

  def clear!
    self.build_output = ""
    self.build_status = false
    self.test_output = ""
    self.test_status = false
    save
  end
end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :builds, dependent: :destroy

  def tag_id(commit)
    "#{name}:#{commit}"
  end
  
  def build_command_string(commit)
    "docker build -t #{tag_id(commit)} ."
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/builds_controller.rb
class BuildsController < ApplicationController
  before_action :set_build, only: [:show, :edit, :update, :destroy, :rebuild]

  # GET /builds
  # GET /builds.json
  def index
    @builds = Build.all
  end

  # GET /builds/1
  # GET /builds/1.json
  def show
  end

  # GET /builds/new
  def new
    @build = Build.new
  end

  # GET /builds/1/edit
  def edit
  end

  # POST /builds
  # POST /builds.json
  def create
    @build = Build.new(build_params)

    respond_to do |format|
      if @build.save
        BuildWorker.perform_async(@build.id)
        format.html { redirect_to @build, notice: 'Build was successfully created.' }
        format.json { render :show, status: :created, location: @build }
      else
        format.html { render :new }
        format.json { render json: @build.errors, status: :unprocessable_entity }
      end
    end
  end

  def rebuild
    @build.clear!

    respond_to do |format|
      BuildWorker.perform_async(@build.id)
      format.html { redirect_to @build, notice: 'Build was successfully created.' }
      format.json { render :show, status: :created, location: @build }
    end
  end

  # PATCH/PUT /builds/1
  # PATCH/PUT /builds/1.json
  def update
    respond_to do |format|
      if @build.update(build_params)
        format.html { redirect_to @build, notice: 'Build was successfully updated.' }
        format.json { render :show, status: :ok, location: @build }
      else
        format.html { render :edit }
        format.json { render json: @build.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /builds/1
  # DELETE /builds/1.json
  def destroy
    @build.destroy
    respond_to do |format|
      format.html { redirect_to builds_url, notice: 'Build was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_build
      @build = Build.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def build_params
      params.require(:build).permit(:name, :commit, :project_id, :build_status, :build_output, :test_status, :test_output, :deployment_status, :deployment_output)
    end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name, :url, :environment, :test_command, :deploy_command)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/builds_helper.rb
module BuildsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/builds/_form.html.erb
<%= form_for(@build) do |f| %>
  <% if @build.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@build.errors.count, "error") %> prohibited this build from being saved:</h2>

      <ul>
      <% @build.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :commit %><br>
    <%= f.text_field :commit %>
  </div>
  <div class="field">
    <%= f.label :project_id %><br>
    <%= f.number_field :project_id %>
  </div>
  <div class="field">
    <%= f.label :build_status %><br>
    <%= f.check_box :build_status %>
  </div>
  <div class="field">
    <%= f.label :build_output %><br>
    <%= f.text_field :build_output %>
  </div>
  <div class="field">
    <%= f.label :test_status %><br>
    <%= f.check_box :test_status %>
  </div>
  <div class="field">
    <%= f.label :test_output %><br>
    <%= f.text_field :test_output %>
  </div>
  <div class="field">
    <%= f.label :deployment_status %><br>
    <%= f.check_box :deployment_status %>
  </div>
  <div class="field">
    <%= f.label :deployment_output %><br>
    <%= f.text_field :deployment_output %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/builds/edit.html.erb
<h1>Editing Build</h1>

<%= render 'form' %>

<%= link_to 'Show', @build %> |
<%= link_to 'Back', builds_path %>

app/views/builds/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Builds</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Commit</th>
      <th>Project</th>
      <th>Build status</th>
      <th>Test status</th>
      <th>Deployment status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @builds.each do |build| %>
      <tr>
        <td><%= build.name %></td>
        <td><%= build.commit %></td>
        <td><%= build.project_id %></td>
        <td><%= build.build_status %></td>
        <td><%= build.test_status %></td>
        <td><%= build.deployment_status %></td>
        <td><%= link_to 'Rebuild', rebuild_build_path(build), method: :post %></td>
        <td><%= link_to 'Show', build %></td>
        <td><%= link_to 'Edit', edit_build_path(build) %></td>
        <td><%= link_to 'Destroy', build, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Build', new_build_path %>

app/views/builds/new.html.erb
<h1>New Build</h1>

<%= render 'form' %>

<%= link_to 'Back', builds_path %>

app/views/builds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @build.name %>
</p>

<p>
  <strong>Commit:</strong>
  <%= @build.commit %>
</p>

<p>
  <strong>Project:</strong>
  <%= @build.project_id %>
</p>

<p>
  <strong>Build status:</strong>
  <%= @build.build_status %>
</p>

<p>
  <strong>Build output:</strong>
  <pre><%= @build.build_output %></pre>
</p>

<p>
  <strong>Test status:</strong>
  <%= @build.test_status %>
</p>

<p>
  <strong>Test output:</strong>
  <pre><%= @build.test_output %></pre>
</p>

<p>
  <strong>Deployment status:</strong>
  <%= @build.deployment_status %>
</p>

<p>
  <strong>Deployment output:</strong>
  <%= @build.deployment_output %>
</p>

<%= link_to 'Rebuild', rebuild_build_path(@build), method: :post %> |
<%= link_to 'Edit', edit_build_path(@build) %> |
<%= link_to 'Back', builds_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DockingStation</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/projects/_form.html.erb
<%= form_for(@project) do |f| %>
  <% if @project.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h2>

      <ul>
      <% @project.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :environment %><br>
    <%= f.text_field :environment %>
  </div>
  <div class="field">
    <%= f.label :test_command %><br>
    <%= f.text_field :test_command %>
  </div>
  <div class="field">
    <%= f.label :deploy_command %><br>
    <%= f.text_field :deploy_command %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/projects/edit.html.erb
<h1>Editing Project</h1>

<%= render 'form' %>

<%= link_to 'Show', @project %> |
<%= link_to 'Back', projects_path %>

app/views/projects/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Projects</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Project URL</th>
      <th>Environment</th>
      <th>Test command</th>
      <th>Deploy command</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @projects.each do |project| %>
      <tr>
        <td><%= project.name %></td>
        <td><%= project.url %></td>
        <td><%= project.environment %></td>
        <td><%= project.test_command %></td>
        <td><%= project.deploy_command %></td>
        <td><%= link_to 'Show', project %></td>
        <td><%= link_to 'Edit', edit_project_path(project) %></td>
        <td><%= link_to 'Destroy', project, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Project', new_project_path %>

app/views/projects/new.html.erb
<h1>New Project</h1>

<%= render 'form' %>

<%= link_to 'Back', projects_path %>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @project.name %>
</p>

<p>
  <strong>Project URL:</strong>
  <%= @project.url %>
</p>

<p>
  <strong>Environment:</strong>
  <%= @project.environment %>
</p>

<p>
  <strong>Test command:</strong>
  <%= @project.test_command %>
</p>

<p>
  <strong>Deploy command:</strong>
  <%= @project.deploy_command %>
</p>

<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>